### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by ralford100** [zbx-sadman/HASP#1]
The following line:
$Objects = $Logins = PropertyEqualOrAny -InputObject $Slots -Property INDEX -Value $LoginId

Should be:
$Objects = $Logins = PropertyEqualOrAny -InputObject $Logins -Property INDEX -Value $LoginId

**Comment by zbx-sadman** [comment]
Thank you for attentive code research. I think that it just copy-paste bug.

I've fix it, but can't complete test soon,

**Comment by ralford100** [comment]
It works beautifully.. thank you for the great utility!
